# 将此文件重命名为xxxx.yaml（其中xxxx可任意拟定，并且不必与tag相同）
# 填写前请先查阅说明文档

# 该用户的标识，可任意拟定
tag: "样例用户"
# 请将双引号内的值替换为该用户的用户名
username: "3212345678"
# 请将双引号内的值替换为该用户的密码
password: "mypassword"
# 此为该用户的登录方式，请勿修改
login_method: "oauth"

# 以井号（#）开头的行是注释，不会被程序读取
# 请不要修改每一行的冒号前的内容
# 在每行填写信息时，除非你知道自己在做什么，否则不建议删除双引号，也不要删除冒号和引号之间的空格
